/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionBD;

/**
 *
 * @author henry.hernandez
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        ConsultaUsuarios(txtCodigo.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        scrUsuarios = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frmUsuarios"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, 45, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 9, 140, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 49, -1, -1));

        jLabel3.setText("EMail");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 83, 38, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 43, 297, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 77, 298, -1));

        jLabel6.setText("Clave");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 117, 38, -1));
        getContentPane().add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 111, 156, -1));

        scrUsuarios.setBackground(new java.awt.Color(255, 255, 204));
        scrUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblUsuarios.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Email", "Tipo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrUsuarios.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblUsuarios.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblUsuarios.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        getContentPane().add(scrUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 650, 190));

        btnBorrar.setText("Borrar");
        btnBorrar.setFocusable(false);
        btnBorrar.setMaximumSize(new java.awt.Dimension(80, 28));
        btnBorrar.setMinimumSize(new java.awt.Dimension(80, 28));
        btnBorrar.setPreferredSize(new java.awt.Dimension(80, 28));
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 77, -1, -1));

        btnInsertar.setText("Insertar");
        btnInsertar.setFocusable(false);
        btnInsertar.setPreferredSize(new java.awt.Dimension(80, 28));
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 43, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.setFocusable(false);
        btnBuscar.setPreferredSize(new java.awt.Dimension(80, 28));
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 6, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.setFocusable(false);
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 111, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ConsultaUsuarios(String usuario) {

        ArrayList<Object[]> lista = null;

        ConexionBD BD = new ConexionBD();

        PreparedStatement ps = null;
        Connection conn = BD.getConexion();
        ResultSet rs = null;

        String vSql = "SELECT CODIGO, NOMBRE, EMAIL, TIPO, ESTADO FROM USUARIOS";
      
        if (!usuario.equals("")) {
           vSql = vSql + " WHERE CODIGO=?";
        }

        try {
            ps = conn.prepareStatement(vSql);
            if (!usuario.equals("")) {
               ps.setString(1, usuario);
            }
            rs = ps.executeQuery();
            while (rs.next()) {
                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }

                lista.add(fila);
            }

            DefaultTableModel modelo = new DefaultTableModel();
            tblUsuarios.setModel(modelo);

            for (int i = 0; i < lista.size(); i++) {
                modelo.addRow(lista.get(i));
            }

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane scrUsuarios;
    public javax.swing.JTable tblUsuarios;
    public javax.swing.JPasswordField txtClave;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
